server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/remark?useSSL=false&serverTimezone=UTC
    username: root
    password: 20020716
  redis:
    host: 192.168.241.130
    port: 6379
#    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.vls.entity # 别名扫描包

logging:
  level:
    com.hmdp: debug