---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LEGION.
--- DateTime: 2023/3/18 16:17
---


if(redis.call('get', KEYS[1] == ARG[1])) then
    return redis.call('del' , KEYS[1])
end
return 0